services:

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/cert:/var/www/cert
      - ./nginx/cert/letsencrypt:/etc/letsencrypt
      - ./nginx/cert/logs:/var/log/letsencrypt
    environment:
      - CERTBOT_EMAIL=goldentechdevelopment@gmail.com
    entrypoint: /bin/sh
    command: [
      "-c",
      "sleep 30 &&
      while true; do
        certbot renew --quiet --post-hook 'kill -HUP $(cat /var/run/nginx.pid)';
        sleep 6h;
      done"
    ]
    networks:
      - network
    restart: on-failure