services:

  db:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env.${APP_ENV}
    ports:
      - "${DB_PORT:-5435}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/db/init:/docker-entrypoint-initdb.d
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-7001}:7001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    env_file:
      - ./.env.${APP_ENV}
      - ./.env.${APP_ENV}.backend
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-5001}:5001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    env_file:
      - ./.env.${APP_ENV}
      - ./.env.${APP_ENV}.frontend
    networks:
      - network
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - SSL_ENABLED=${SSL_ENABLED:-false}
    env_file:
      - ./.env.${APP_ENV}
    volumes:
      - ./nginx/cert:/var/www/cert
      - ./nginx/cert/letsencrypt:/etc/letsencrypt
    networks:
      - network
    depends_on:
      - backend
      - frontend

networks:
  network:
    driver: bridge

volumes:
  db_data:
    # external: true # if volume is already exists
