include:
  - base.yaml
  - networks.yaml

name: hic_dev

services:
  backend:
    container_name: hic-backend-dev
    build:
      context: ../../
      dockerfile: apps/backend/Dockerfile
      args:
        NODE_ENV: production
    image: ${REGISTRY_URL:-localhost:5007}/backend:${VERSION:-dev}
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:8080}
    ports:
      - "3011:3011"
    profiles:
      - dev
    networks:
      - hicnet
    deploy:
      resources:
        limits:
          memory: 512M

  auth-service:
    container_name: hic-auth-service-dev
    build:
      context: ../../
      dockerfile: apps/auth-service/Dockerfile
      args:
        NODE_ENV: production
    image: ${REGISTRY_URL:-localhost:5007}/auth-service:${VERSION:-dev}
    environment:
      NODE_ENV: production
      AUTH_PORT: 3012
      AUTH_DATABASE_URL: postgresql://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth-db:5432/${AUTH_DB_NAME}
      JWT_SECRET: ${JWT_SECRET:?err}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
    ports:
      - "3012:3012"
    profiles:
      - dev
    networks:
      - hicnet
    deploy:
      resources:
        limits:
          memory: 512M

  worker-service:
    container_name: hic-worker-service-dev
    build:
      context: ../../
      dockerfile: apps/worker-service/Dockerfile
      args:
        NODE_ENV: production
    image: ${REGISTRY_URL:-localhost:5007}/worker-service:${VERSION:-dev}
    environment:
      NODE_ENV: production
      WORKER_SERVICE_PORT: 5000
      BACKEND_URL: http://backend:3011
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_URL: redis://redis:6379
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
    ports:
      - "5000:5000"
    profiles:
      - dev
    networks:
      - hicnet
    deploy:
      resources:
        limits:
          memory: 512M

  bff:
    container_name: hic-bff-dev
    build:
      context: ../../
      dockerfile: apps/bff/Dockerfile
      args:
        NODE_ENV: production
    image: ${REGISTRY_URL:-localhost:5007}/bff:${VERSION:-dev}
    environment:
      NODE_ENV: production
      BFF_PORT: ${BFF_PORT:-3010}
      BACKEND_URL: http://backend:3011
      AUTH_SERVICE_URL: http://auth-service:3012/api/auth
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:8080}
    ports:
      - "3010:3010"
    profiles:
      - dev
    networks:
      - hicnet
    deploy:
      resources:
        limits:
          memory: 512M

  frontend:
    container_name: hic-frontend-dev
    build:
      context: ../../
      dockerfile: apps/frontend/Dockerfile
      args:
        NODE_ENV: production
    image: ${REGISTRY_URL:-localhost:5007}/frontend:${VERSION:-dev}
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BFF_URL: ${NEXT_PUBLIC_BFF_URL:-http://localhost:8080/bff}
    ports:
      - "3000:3000"
    profiles:
      - dev
    networks:
      - hicnet
    deploy:
      resources:
        limits:
          memory: 512M
