include:
  - networks.yaml

services:
  nginx:
    container_name: hic-nginx-${APP_ENV:-dev}
    image: ${NGINX_IMAGE:-${REGISTRY_URL:-ghcr.io/eugeneazdev/hic}/nginx:${VERSION:-staging-latest}}
    pull_policy: ${NGINX_PULL_POLICY:-always}
    restart: unless-stopped
    profiles:
      - dev
      - qa
      - staging
      - prod
    ports:
      - "${NGINX_HTTP_PORT:-8080}:80"
      - "${NGINX_HTTPS_PORT:-8443}:443"
    environment:
      - SSL_ENABLED=${SSL_ENABLED:-false}
      - DOMAIN=${DOMAIN:-localhost}
    volumes:
      - /opt/hic/infra/nginx/ssl:/etc/letsencrypt
      - /opt/hic/infra/nginx/cert:/var/www/cert
    networks:
      - hicnet
    depends_on:
    - bff
    - auth-service
    - backend
    - frontend
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
