include:
  - base.yaml
  - networks.yaml

name: hic_staging

services:
  backend:
    container_name: hic-backend-staging
    image: ${REGISTRY_URL:-ghcr.io/eugeneazdev/hic}/backend:${VERSION:-staging-latest}
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3001}
    ports:
      - "3013:3011"
    networks:
      - hicnet
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: unless-stopped

  auth-service:
    container_name: hic-auth-service-staging
    image: ${REGISTRY_URL:-ghcr.io/eugeneazdev/hic}/auth-service:${VERSION:-staging-latest}
    environment:
      NODE_ENV: production
      AUTH_PORT: 3012
      AUTH_DATABASE_URL: postgresql://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth-db:5432/${AUTH_DB_NAME}
      JWT_SECRET: ${JWT_SECRET:?err}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
    ports:
      - "3014:3012"
    networks:
      - hicnet
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: unless-stopped

  worker-service:
    container_name: hic-worker-service-staging
    image: ${REGISTRY_URL:-ghcr.io/eugeneazdev/hic}/worker-service:${VERSION:-staging-latest}
    environment:
      NODE_ENV: production
      WORKER_SERVICE_PORT: 5000
      BACKEND_URL: http://backend:3011
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_URL: redis://redis:6379
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
    ports:
      - "5001:5000"
    networks:
      - hicnet
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: unless-stopped

  bff:
    container_name: hic-bff-staging
    image: ${REGISTRY_URL:-ghcr.io/eugeneazdev/hic}/bff:${VERSION:-staging-latest}
    environment:
      NODE_ENV: production
      BFF_PORT: ${BFF_PORT:-3010}
      BACKEND_URL: http://backend:3011
      AUTH_SERVICE_URL: http://auth-service:3012/api/auth
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3001}
    ports:
      - "3015:3010"
    networks:
      - hicnet
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: unless-stopped

  frontend:
    container_name: hic-frontend-staging
    image: ${REGISTRY_URL:-ghcr.io/eugeneazdev/hic}/frontend:${VERSION:-staging-latest}
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BFF_URL: ${NEXT_PUBLIC_BFF_URL:-https://hic-staging.gtechdev.top/bff}
      NEXT_PUBLIC_AUTH_SERVICE_URL: ${NEXT_PUBLIC_AUTH_SERVICE_URL:-https://hic-staging.gtechdev.top/bff/auth}
    ports:
      - "3001:3000"
    volumes:
      - /opt/hic/apps/frontend/public:/app/apps/frontend/public:ro
    networks:
      - hicnet
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: unless-stopped

